version: '3.9'

services:
  postgres:
    container_name: postgres_strap_monitora
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ~/apps/postgres/monitora:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: monitora
      POSTGRES_DB: monitora